import { ClerkProvider } from "@clerk/nextjs";
import { SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <div className="relative">
              <Navbar />
            </div>
            <div className="absolute right-28 top-5 flex items-center text-white">
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton
                  showName
                  appearance={{
                    variables: {
                      colorText: "#ffffff", // Custom text color
                    },
                    elements: {
                      userButtonName: "text-white", // Ensure name text is white
                    },
                  }}
                />
              </SignedIn>
            </div>
          </header>

          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
